- hosts: all
  become: yes
  vars:
    jenkins_hostname: localhost
    jenkins_admin_username: jenkinsadm
    jenkins_admin_password: GLS-redhat123!
#    jenkins_admin_password_file: /var/lib/jenkins/secrets/initialAdminPassword
    jenkins_plugins: [ aws-java-sdk, bitbucket, blueocean, blueocean-bitbucket-pipeline, blueocean-core-js, blueocean-pipeline-editor, bouncycastle-api, blueocean-commons, blueocean-config, config-file-provider, blueocean-dashboard, jenkins-design-language, durable-task, email-ext, blueocean-events, git-parameter, blueocean-git-pipeline, blueocean-github-pipeline, blueocean-i18n, jira, blueocean-jira, openshift-client, blueocean-jwt, pam-auth, blueocean-personalization, blueocean-pipeline-api-impl, blueocean-pipeline-scm-api, workflow-basic-steps, pipeline-model-definition, pipeline-model-extensions, workflow-cps, workflow-job, pipeline-model-api, workflow-durable-task-step, workflow-cps-global-lib, pipeline-stage-tags-metadata, build-pipeline-plugin, blueocean-rest, blueocean-rest-impl, rocketchatnotifier, script-security, ssh-slaves, run-condition, workflow-support, blueocean-web, junit ]
    jenkins_plugins_install_dependencies: true
  tasks:
    - name: install Java
      include_role:
        name: geerlingguy.java
#    - name: get remote jenkins admin password file
#      slurp:
#        src: "{{ jenkins_admin_password_file }}" 
#      register: adminpasswordfile
#      no_log: False
#      when: jenkins_admin_password_file != "" 
#    - name: set jenkins admin password
#      set_fact:
#        jenkins_admin_password: "{{ adminpasswordfile.content | b64decode | trim }}"
#      no_log: True
    - name: install jenkins
      include_role:
        name: geerlingguy.jenkins
